apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - eks-console
      rolearn: arn:aws:iam::<account-number>:role/eksctl-test-cluster-nodegroup-lin-NodeInstanceRole-TP9OA03U6A0M
      username: system:node:{{EC2PrivateDNSName}}
  
  mapUsers: |
    - userarn: arn:aws:iam::<account-number>:root
      groups:
      - system:bootstrappers
      - system:nodes
      - eks-console
      - system:masters
    
    - userarn: arn:aws:iam::<account-number>:user/<your-user-name>
      groups:
      - system:bootstrappers
      - system:nodes
      - eks-console
      - system:masters


kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
